### ISSUE TITLE
id-match rule rejects properties prefixed with $

### ISSUE THREAD

**Issue by trevorsmith** [gajus/eslint-config-canonical#12]
The `id-match` rule rejects object properties prefixed with `$`, which are required to [configure ajv](https://github.com/epoberezkin/ajv#data-reference). Quoting the property results in a different linting error, `quote-props`. [See this issue for a real-world example.](https://github.com/gajus/babel-plugin-react-css-modules/pull/116#issuecomment-322531055)

I'd modify the `id-match` regular expression myself and submit a pull request but I'm not entirely sure what it is currently intended to match.

**Comment by gajus** [comment]
Just use `// eslint-disable-next-line id-match` for edge cases.
