### ISSUE TITLE
`space-before-function-paren` for named functions

### ISSUE THREAD

**Issue by RA80533** [gajus/eslint-config-canonical#30]
The configuration disallows traditional *f*()-like parenthesis placement for named functions. Is this intended? I couldn't find any instances of named functions in your code to determine if this was a conscious decision for named functions specifically. It appears that you mostly use the arrow syntax, for which this rule makes sense.

```js
// Error
function ln(x) {
    return Math.log(x);
}

ln(2); // => ~0.693
```

```js
// No error
async function name ({ id }, database) {
    return database.getName(id);
}

await name(card, "localhost");
```

**Comment by gajus** [comment]
There is no reason this cannot be used with named functions.

What's the concern?

The purpose of the rule is to clearly distinguish function declaration and function invocation.
