### ISSUE TITLE
Change @typescript-eslint/return-await to in-try-catch

### ISSUE THREAD

**Issue by agirorn** [gajus/eslint-config-canonical#36]
I would recommend changing [@typescript-eslint/return-await](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/return-await.md) to error in [in-try-catch](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/return-await.md#in-try-catch) instead of always to prevent async code from taking on the performance hit of having a microtask just to await the promise in the current stack. See [no-return-await](https://eslint.org/docs/rules/no-return-await) for more details.

**Comment by gajus** [comment]
Vast majority of codebases will never benefit from that that microtask optimization, but they will benefit daily from better stack trace. In those codebases where this matters, just disable that rule.
