### ISSUE TITLE
`sort-keys` autofix is case-sensitive

### ISSUE THREAD

**Issue by NimmLor** [gajus/eslint-config-canonical#43]
In a Json document, the autofix for `sort-keys` is case-sensitive, resulting in an error for `jsonc/sort-keys`` which is case-insensitive

> Expected object keys to be in natural insensitive ascending order. 'usernamePasswordIsEnabled' should be before 'userPoolRegion'. eslint (jsonc/sort-keys)

code produced after autofix:
```json
{
  "userPoolId": "eu-central-1_xxxx",
  "userPoolRegion": "eu-central-1",
  "usernamePasswordIsEnabled": true
}
```

**Comment by gajus** [comment]
Could you submit a patch to config?

**Comment by NimmLor** [comment]
Sure, will do that tommorow 👍🏻

**Comment by NimmLor** [comment]
Ok, after some time digging I couldn't find the issue. Changing `jsonc/sort-keys` had no effect on the autofix. Setting `caseSensitive: true` removes the error, but it is sorted sensitive.

**Comment by gajus** [comment]
So is this a bug in jsonc plugin? CC @ota-meshi

**Comment by gajus** [comment]
Closing as there is lack of context.
