### ISSUE TITLE
jest doc blocks clash with jsdoc/check-tag-names

### ISSUE THREAD

**Issue by lucasrmendonca** [gajus/eslint-config-canonical#49]
Jest test environments are now recommended to be set per-file to improve performance by adding a `@jest-environment` docblock at the top of the file:

```
/**
 * @jest-environment jsdom
 */
```
https://jestjs.io/docs/configuration#testenvironment-string

However, this is clashing with rule Check Tag Names https://github.com/gajus/eslint-plugin-jsdoc/blob/master/.README/rules/check-tag-names.md

My suggestion:
For config `canonical/jest`, either disable the check-tag-names rule or modify its options so it classifies docblocks written as `@jest-environment **` as valid

**Comment by gajus** [comment]
Is it only `jest-environment` tag?

**Comment by lucasrmendonca** [comment]
> Is it only `jest-environment` tag?

@jest-environment and @jest-environment-options
