### ISSUE TITLE
`This experimental syntax requires enabling one of the following parser plugin(s): ‘jsx, flow, typescript’`

### ISSUE THREAD

**Issue by lucasrmendonca** [gajus/eslint-config-canonical#50]
When linting .jsx files I have the following error:
`This experimental syntax requires enabling one of the following parser plugin(s): ‘jsx, flow, typescript’`

My .eslintrc.json config file is as follows:
```
{
  "settings": { "import/extensions": [".js", ".jsx"] },
  "ignorePatterns": ["node_modules/"],
  "parserOptions": {
    "ecmaVersion": "latest",
    "ecmaFeatures": { "jsx": true },
  },
  "extends": ["canonical", "canonical/prettier"],
  "overrides": [
    {
      "files": "*.jsx",
      "extends": ["canonical/react"]
    }
  ]
}
```

If I install "@babel/preset-react" with npm and add the following property to "parserOptions", the error goes away and `.jsx` files are then linted normally:

```
"parserOptions": {
   ...
   "babelOptions": {
      "presets": ["@babel/preset-react"]
   },
   ...
},
```

However, I'm not sure this is the intended way to use the "canonical/react" config since there's no mention of it in the docs...

If `@babel/preset-react` is required, shouldn't it already come inside the `canonical/react` config? 
If it's not required, could someone kindly provide a working example using "canonical/react" with ".jsx" instead of ".tsx"?

**Comment by beuluis** [comment]
same for me
