### ISSUE TITLE
Definition for the NextJS rules not found

### ISSUE THREAD

**Issue by yanislav-igonin** [gajus/eslint-config-canonical#60]
Have a simple NextJS project on the typescript.

This is my `.eslintrc`:
![SCR-20230205-iab](https://user-images.githubusercontent.com/15846431/216815453-66baff15-2532-4f5e-bfa0-eb7b4380530d.png)

I'm getting those errors in each file on top of the files:
![SCR-20230205-ia4](https://user-images.githubusercontent.com/15846431/216815462-55cf54b9-2adb-49d7-9521-8261d0489b97.png)

I tried to extend also from the `eslint-config-next` config that is coming with the nextjs by defalt, but the linter said that those rules sets are conflicting.

Then I tried to uninstall `eslint-config-next` from the project, another errors occurred:
![image](https://user-images.githubusercontent.com/15846431/216815687-28c7dfd0-1ab1-4726-8087-3657932242c3.png)

What can be a problem, guys?
Maybe I should change order of extended rules sets?

Thanks in advance for the any info!

**Comment by iamseye** [comment]
@yanislav-igonin I had similar errors, and I changed the extends from `canonical/next` to `next` and added `eslint-config-next`. the errors went away.

**Comment by yanislav-igonin** [comment]
> @yanislav-igonin I had similar errors, and I changed the extends from `canonical/next` to `next` and added `eslint-config-next`. the errors went away.

thanks for the info, will try this one :)
