### ISSUE TITLE
Add `paths/alias` rule, to fix path aliases automatically

### ISSUE THREAD

**Issue by vitonsky** [gajus/eslint-config-canonical#82]
Hi, what about add a rule `paths/alias` in [eslint-plugin-paths](https://github.com/vitonsky/eslint-plugin-paths) plugin?

It analyzes `tsconfig.json` and reports a relative paths in imports that must be replaced to a path aliases like `@foo/x/y`.

This rule supports an auto fix, and option for excluded paths [in development](https://github.com/vitonsky/eslint-plugin-paths/issues/28), so in next versions user may just add deprecated paths or alias names in rule options and aliases will be reverted to relative paths back. This plugin automate control over aliases management

**Comment by gajus** [comment]
We already use https://github.com/gajus/eslint-plugin-canonical?tab=readme-ov-file#prefer-import-alias for this.

I don't know about including either into the default config.
