### ISSUE TITLE
Could not resolve dependency: `npm error peer eslint@"^8.30.0" from eslint-config-canonical@43.0.12`

### ISSUE THREAD

**Issue by lucasrmendonca** [gajus/eslint-config-canonical#84]
When trying to install version  43.0.12 in a project using eslint 9.4.0 I am getting the following error:

```sh
npm error Could not resolve dependency:
npm error peer eslint@"^8.30.0" from eslint-config-canonical@43.0.12
```

**Comment by wallzero** [comment]
Perhaps also related?

> Error: Cannot read config file: /node_modules/eslint-config-canonical/eslintrc.js
> Error: Cannot find module './configurations/eslintrc'

**Comment by web-dev-sam** [comment]
Same here

**Comment by lucasrmendonca** [comment]
I think to fix this error the following line should probably be updated to `eslint@"^9.0.0"`, can you confirm @gajus ?

https://github.com/gajus/eslint-config-canonical/blob/c3e341f6334062be6a117a50a59756ed39d983a8/package.json#L75

**Comment by web-dev-sam** [comment]
For those who can't or didnt bother updating to eslint 9 yet, downgrade eslint-config-canonical to the latest 42 major version.

**Comment by lucasrmendonca** [comment]
Hi @gajus friendly reminder: could you check if this peerDependency is correct?

> I think to fix this error the following line should probably be updated to `eslint@"^9.0.0"`, can you confirm @gajus ?
> 
> https://github.com/gajus/eslint-config-canonical/blob/c3e341f6334062be6a117a50a59756ed39d983a8/package.json#L75
